/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT */

export enum ServerPaddleSide {
  Left = 0,
  Right = 1,
}

export enum ServerState {
  Play = 0,
  Starting = 1,
}

export interface IMessageClientConfig {
    /**
     * The general configuration of the game
     */
    gameConfig: IMessageConfig;
    /**
     * Which side the receiving client is on
     */
    playerSide: ServerPaddleSide;
}

export interface IMessageConfig {
    paddleHeight: number;
    paddleWidth: number;
    ballRadius: number;
    paddleMaxSpeedPerSecond: number;
}

export interface IMessageInput {
    /**
     * Movement axis in range [-1,1]
     */
    m: number;
    /**
     * Duration in seconds
     */
    d: number;
    /**
     * Input index
     */
    n: number;
}

export interface IMessageState {
    /**
     * The actual state data.  Each state should understand its own schema.
     */
    s: any;
    /**
     * The state type this message describes.
     */
    t: ServerState;
    /**
     * The last input index for this client seen by the server.
     */
    n: number;
}
