//+build ignore

package main

import (
	"log"
	"os"

	"github.com/Evertras/go-ts-type-generator/typegen"
	"github.com/Evertras/gopong/lib/state/play"
)

func main() {
	generator := typegen.NewWithConfig(typegen.Config{
		Indentation: "    ",
		Prefix:      "MessagePlay",
	})

	outfile, err := os.Create("../../../front/src/game/states/play/messageTypes.ts")

	if err != nil {
		log.Panic(err)
	}

	defer outfile.Close()

	outfile.WriteString("/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT */\n\n")

	err = generator.GenerateTypes(
		outfile,
		play.State{},
	)

	if err != nil {
		log.Fatal(err)
	}

	outfile.WriteString("\n")
}
