//+build ignore

package main

import (
	"log"
	"os"

	"github.com/Evertras/go-ts-type-generator/typegen"
	"github.com/Evertras/gopong/lib/message"
)

func main() {
	generator := typegen.NewWithConfig(typegen.Config{
		Indentation: "    ",
		Prefix:      "Message",
	})

	outfile, err := os.Create("../../front/src/network/messageTypes.ts")

	if err != nil {
		log.Panic(err)
	}

	defer outfile.Close()

	outfile.WriteString("/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT */\n\n")

	outfile.WriteString(`export enum ServerPaddleSide {
  Left = 0,
  Right = 1,
}

export enum ServerState {
  Play = 0,
  Starting = 1,
}

`)

	err = generator.GenerateTypes(
		outfile,
		message.ClientConfig{},
		message.Input{},
		message.State{},
	)

	if err != nil {
		log.Fatal(err)
	}

	outfile.WriteString("\n")
}
