// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client.proto

package gopongmsg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Client struct {
	// Types that are valid to be assigned to Msg:
	//	*Client_Input_
	Msg                  isClient_Msg `protobuf_oneof:"msg"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}
func (*Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{0}
}

func (m *Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client.Unmarshal(m, b)
}
func (m *Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client.Marshal(b, m, deterministic)
}
func (m *Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client.Merge(m, src)
}
func (m *Client) XXX_Size() int {
	return xxx_messageInfo_Client.Size(m)
}
func (m *Client) XXX_DiscardUnknown() {
	xxx_messageInfo_Client.DiscardUnknown(m)
}

var xxx_messageInfo_Client proto.InternalMessageInfo

type isClient_Msg interface {
	isClient_Msg()
}

type Client_Input_ struct {
	Input *Client_Input `protobuf:"bytes,1,opt,name=input,proto3,oneof"`
}

func (*Client_Input_) isClient_Msg() {}

func (m *Client) GetMsg() isClient_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *Client) GetInput() *Client_Input {
	if x, ok := m.GetMsg().(*Client_Input_); ok {
		return x.Input
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Client) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Client_Input_)(nil),
	}
}

type Client_Input struct {
	MovementAxis         float32  `protobuf:"fixed32,1,opt,name=movement_axis,json=movementAxis,proto3" json:"movement_axis,omitempty"`
	DurationSeconds      float32  `protobuf:"fixed32,2,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	InputIndex           uint32   `protobuf:"varint,3,opt,name=input_index,json=inputIndex,proto3" json:"input_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Client_Input) Reset()         { *m = Client_Input{} }
func (m *Client_Input) String() string { return proto.CompactTextString(m) }
func (*Client_Input) ProtoMessage()    {}
func (*Client_Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{0, 0}
}

func (m *Client_Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client_Input.Unmarshal(m, b)
}
func (m *Client_Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client_Input.Marshal(b, m, deterministic)
}
func (m *Client_Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client_Input.Merge(m, src)
}
func (m *Client_Input) XXX_Size() int {
	return xxx_messageInfo_Client_Input.Size(m)
}
func (m *Client_Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Client_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Client_Input proto.InternalMessageInfo

func (m *Client_Input) GetMovementAxis() float32 {
	if m != nil {
		return m.MovementAxis
	}
	return 0
}

func (m *Client_Input) GetDurationSeconds() float32 {
	if m != nil {
		return m.DurationSeconds
	}
	return 0
}

func (m *Client_Input) GetInputIndex() uint32 {
	if m != nil {
		return m.InputIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*Client)(nil), "gopongmsg.Client")
	proto.RegisterType((*Client_Input)(nil), "gopongmsg.Client.Input")
}

func init() { proto.RegisterFile("client.proto", fileDescriptor_014de31d7ac8c57c) }

var fileDescriptor_014de31d7ac8c57c = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0xcf, 0xc1, 0x0a, 0x82, 0x30,
	0x1c, 0xc7, 0xf1, 0xa6, 0x28, 0xf4, 0x57, 0x29, 0x76, 0x49, 0xba, 0x24, 0x75, 0xb1, 0xcb, 0x82,
	0x7a, 0x82, 0xea, 0x92, 0x57, 0x7b, 0x00, 0x31, 0x1d, 0x63, 0xd0, 0x36, 0x71, 0x33, 0xf6, 0x6c,
	0x3d, 0x5d, 0x38, 0xb1, 0xeb, 0xe7, 0xf7, 0x65, 0xe3, 0x0f, 0x71, 0xf3, 0xe6, 0x54, 0x1a, 0xd2,
	0xf5, 0xca, 0x28, 0xbc, 0x64, 0xaa, 0x53, 0x92, 0x09, 0xcd, 0xf6, 0x5f, 0x04, 0xe1, 0xdd, 0x6d,
	0xf8, 0x04, 0x01, 0x97, 0xdd, 0x60, 0x52, 0x94, 0xa1, 0x3c, 0x3a, 0x6f, 0xc8, 0xbf, 0x22, 0x53,
	0x41, 0x8a, 0x71, 0x7e, 0x2c, 0xca, 0xa9, 0xdb, 0x5a, 0x08, 0x9c, 0xe0, 0x03, 0x24, 0x42, 0x7d,
	0xa8, 0xa0, 0xd2, 0x54, 0xb5, 0xe5, 0xda, 0xbd, 0xe0, 0x95, 0xf1, 0x8c, 0x57, 0xcb, 0x35, 0x3e,
	0xc2, 0xba, 0x1d, 0xfa, 0xda, 0x70, 0x25, 0x2b, 0x4d, 0x1b, 0x25, 0x5b, 0x9d, 0x7a, 0xae, 0x5b,
	0xcd, 0xfe, 0x9c, 0x18, 0xef, 0x20, 0x72, 0x3f, 0x54, 0x5c, 0xb6, 0xd4, 0xa6, 0x7e, 0x86, 0xf2,
	0xa4, 0x04, 0x47, 0xc5, 0x28, 0xb7, 0x00, 0x7c, 0xa1, 0xd9, 0x2b, 0x74, 0xe7, 0x5c, 0x7e, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x29, 0x7c, 0xfa, 0x17, 0xde, 0x00, 0x00, 0x00,
}
