// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2018-12-14 21:23:52.8317503 -0800 PST m=+0.002992901
package lib

var indexContents = `<html>
    <head>
        <title>Go Pong</title>
    </head>
    <body>
        Hello
    </body>
</html>`