version: '3'

services:

  traefik:
    image: traefik:alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./etc/traefik.toml:/traefik.toml:ro
    ports:
      - "80:80"
    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host: traefik.localhost"
      traefik.backend: traefik
      traefik.port: 8001
    networks:
      - gopong

  gopong:
    image: evertras/gopong:latest
    command: --statsd telegraf:8125 --prometheus :9001
    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host: gopong.localhost"
      traefik.backend: gopong
      traefik.port: 8000
    networks:
      - gopong

  telegraf:
    image: telegraf:1.4.0
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - gopong

  influxdb:
    image: influxdb:1.3.5
    networks:
      - gopong

  chronograf:
    image: chronograf:1.3.8
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host: chronograf.localhost,metrics.localhost"
      traefik.backend: chronograf
      traefik.port: 8888
    networks:
      - gopong

  kapacitor:
    image: kapacitor:1.3.3
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    networks:
      - gopong

  prometheus:
    image: prom/prometheus
    volumes:
      - ./etc/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml"
    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host: prometheus.localhost,prom.localhost"
      traefik.backend: prometheus
      traefik.port: 9090
    networks:
      - gopong

networks:
  gopong:
