# Stolen and modified from https://github.com/influxdata/TICK-docker
version: '3'

services:

  #telegraf:
    #image: telegraf:1.4.0
    #volumes:
      #- ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    #ports:
      #- "8092:8092/udp"
      #- "8094:8094"
      #- "8125:8125/udp"

  influxdb:
    image: influxdb:1.3.5
    volumes:
      - influx:/var/lib/influxdb
    ports:
      - "8086:8086"

  chronograf:
    image: chronograf:1.3.8
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
    ports:
      - "8888:8888"

  kapacitor:
    image: kapacitor:1.3.3
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    ports:
      - "9092:9092"
volumes:
  influx:
