scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gopong'
    scrape_interval: 10s
    static_configs:
      - targets: ['gopong:9001']

  - job_name: 'traefik'
    scrape_interval: 10s
    static_configs:
      - targets: ['traefik:8000']
