# Serious WIP here...

#defaultEntryPoints = ["http", "https"]
defaultEntryPoints = ["http"]

# Totally insecure, only use for dev
[api]
entryPoint = "traefik"
dashboard = true

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "localhost"
exposedByDefault = false

[metrics]
    [metrics.prometheus]
        entryPoint = "metrics"
        buckets = [0.1,0.3,1.2,5.0]
    [metrics.statsd]
        address = "telegraf:8125"
        pushInterval = "10s"

[entryPoints]
    [entryPoints.http]
    address = ":80"
    [entryPoints.metrics]
    address = ":8000"
    [entryPoints.traefik]
    address = ":8001"

    # Fix all this when LetsEncrypt is figured out... low priority
    #[entryPoints.https]
    #address = ":443"
        #[entryPoints.https.tls]
#[acme]
#email = "bfullj@gmail.com"
#storage = "acme.json"
#entryPoint = "https"
#onHostRule = true
#onDemand = false
